--https://school.programmers.co.kr/learn/courses/30/lessons/164673
--oracle


   SELECT USED_GOODS_BOARD.TITLE
        , USED_GOODS_BOARD.BOARD_ID
        , USED_GOODS_REPLY.REPLY_ID
        , USED_GOODS_REPLY.WRITER_ID
        , USED_GOODS_REPLY.CONTENTS
        , to_char(USED_GOODS_REPLY.CREATED_DATE, 'yyyy-mm-dd') AS CREATED_DATE
     FROM USED_GOODS_BOARD
LEFT JOIN USED_GOODS_REPLY
       ON USED_GOODS_BOARD.BOARD_ID = USED_GOODS_REPLY.BOARD_ID
    WHERE to_char(USED_GOODS_BOARD.CREATED_DATE, 'yyyy-mm') = '2022-10'
      AND USED_GOODS_REPLY.REPLY_ID IS NOT NULL
 ORDER BY USED_GOODS_REPLY.CREATED_DATE
        , USED_GOODS_BOARD.TITLE
