--https://school.programmers.co.kr/learn/courses/30/lessons/131114
--MYSQL


  SELECT WAREHOUSE_ID
       , WAREHOUSE_NAME
       , ADDRESS
       , COALESCE(FREEZER_YN, "N") AS FREEZER_YN
    FROM FOOD_WAREHOUSE
   WHERE WAREHOUSE_NAME LIKE '%경기%'
ORDER BY WAREHOUSE_ID
